CREATE TABLE IF NOT EXISTS users (
    id         BIGSERIAL PRIMARY KEY,
    username   VARCHAR(32) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Migrates databases created before authentication was removed.
DROP TABLE IF EXISTS auth_tokens;
ALTER TABLE users DROP COLUMN IF EXISTS password_hash;

CREATE TABLE IF NOT EXISTS messages (
    id            BIGSERIAL PRIMARY KEY,
    sender_id     BIGINT        NOT NULL REFERENCES users(id),
    recipient_id  BIGINT        NOT NULL REFERENCES users(id),
    body          VARCHAR(4000) NOT NULL,
    -- Generated by the browser. A client that resends after a flaky connection
    -- (it never saw the ack) must not create a duplicate message, so (sender, client id)
    -- is unique and a duplicate insert returns the original row instead.
    client_msg_id VARCHAR(64)   NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    read_at       TIMESTAMPTZ,
    UNIQUE (sender_id, client_msg_id)
);

-- History is always fetched per pair of users, newest first, so index both directions.
CREATE INDEX IF NOT EXISTS idx_messages_pair ON messages (sender_id, recipient_id, id);
CREATE INDEX IF NOT EXISTS idx_messages_recipient_unread ON messages (recipient_id) WHERE read_at IS NULL;
